TecHub/urls.py
from django.conf.urls.static import static
from django.urls import path

from core import settings
from .views import home, login, hub_digital, open_finance, instituicao_view, realiza_cambio, realiza_tranferencia

app_name = 'TecHub'

urlpatterns = [
    path('', home, name='home'),
    path('login/', login, name='login'),
    path('hub/', hub_digital, name='hub'),
    path('openfinance/', open_finance, name='open_finance'),
    path('hub/banco/<pk>', instituicao_view, name='instituicao_view'),
    path('hub/banco/<pk>/cambio', realiza_cambio, name='realiza_cambio'),
    path('hub/banco/<pk>/transferencia', realiza_tranferencia, name='realiza_tranferencia'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('TecHub.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

TecHub/models.py
from django.db import models
from django.contrib.auth.models import User


# INSTITUIÇÕES FINANCEIRAS
class Instituicao(models.Model):
    nome = models.CharField(
        max_length=100,
        null=False
    )

    foto_instituicao = models.ImageField(
        upload_to='img',
        null=True,
    )

    def __str__(self):
        nome = self.nome.split('-')[1].strip()
        return nome


# Info Cliente Instituição
# Agencia
# Conta
# Login
# Senha
# Usuario
# Saldo Conta
# Saldo DREX
class InfoClienteInstituicao(models.Model):  # Simula o banco de dados da instituição bancária do cliente
    Instituicao = models.ForeignKey(
        Instituicao,
        on_delete=models.CASCADE,
        null=False,
        blank=False
    )


    agencia = models.CharField(
        max_length=5,
        null=False,
        blank=False
    )

    conta = models.CharField(
        null=False,
        blank=False,
        max_length=9
    )

    senha = models.CharField(
        max_length=12,
        null=False,
        blank=False
    )

    usuario = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False,
        blank=False
    )

    saldo_bancario = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        null=True,
        blank=True
    )

    saldo_drex = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        null=True,
        blank=True
    )


# CARTEIRAS CLIENTE
class InformacaoClienteOpenFinance(models.Model):
    usuario = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='usuario'
    )

    instituicao_user = models.ForeignKey(
        Instituicao,
        on_delete=models.CASCADE,
        related_name='instituicao_user'
    )

    info_instituicao_user = models.ForeignKey(
        InfoClienteInstituicao,
        on_delete=models.CASCADE,
        related_name='info_instituicao_user'
    )


# Items Navegação
class NavItem(models.Model):
    nome = models.CharField(
        max_length=50,
        null=True
    )

    url = models.CharField(
        max_length=100,
        null=True
    )

    icone = models.TextField(
        max_length=500,
        null=True
    )

    pagina = models.CharField(
        max_length=100,
        null=True
    )

TecHub/forms.py
from django import forms
from .models import Instituicao, InformacaoClienteOpenFinance, InfoClienteInstituicao
from django.core.exceptions import ValidationError
from django.core.exceptions import ValidationError

from django.utils.translation import gettext_lazy as _


class FormLogin(forms.Form):
    login = forms.CharField(max_length=30)
    senha = forms.CharField(widget=forms.PasswordInput)


class CambioForm(forms.Form):
    valor_cambio = forms.CharField(
        max_length=15,
        required=True,
        label='Valor câmbio',
        label_suffix='',
    )

    valor_cambio.widget.attrs.update(
        {'placeholder': 'Insira o valor'}
    )


MOEDAS = [
    (1, 'DREX'),
    (2, 'e-CNY'),
    (3, 'Digital Euro '),
    (4, 'Digital Dollar ')
]

# class TransferenciaForm(forms.Form):
#     moeda_origem = forms.ChoiceField(
#         label="Moeda de destino",
#         choices=MOEDAS)

#     valor_trasferencia = forms.DecimalField(
#         decimal_places=2
#     )

#     saldo_drex = forms.DecimalField(
#         decimal_places=2,
#         required=True
#     )

TecHub/views.py
from django.contrib.auth import authenticate, login as login_django
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from TecHub.forms import FormLogin
from TecHub.models import NavItem, Instituicao, InfoClienteInstituicao, InformacaoClienteOpenFinance
import datetime
import locale
from .forms import CambioForm
from django.core.exceptions import ValidationError
from decimal import Decimal
from django.contrib import messages
import requests


def cria_data_por_extenso():
    locale.setlocale(locale.LC_ALL, 'pt_BR')
    data = datetime.date.today()
    dia_semana = datetime.datetime.strftime(data, '%A').title()
    dia = datetime.datetime.strftime(data, '%d')
    mes = datetime.datetime.strftime(data, '%B').title()
    ano = datetime.datetime.strftime(data, '%Y')
    return f'{dia_semana} {dia} de {mes} de {ano}'


def verifica_existencia_registro(id_conta_user, id_user, id_instituicao_user):
    verificacao = InformacaoClienteOpenFinance.objects.get(
        info_instituicao_user_id=id_conta_user,
        instituicao_user_id=id_instituicao_user,
        usuario_id=id_user
    )
    if verificacao:
        return True
    return False


def home(request):
    if request.method == 'GET':
        return render(request, template_name='techub/index.html')


def login(request: HttpRequest):
    if request.method == 'GET':
        form = FormLogin()
        context = {
            'form': form
        }
        return render(request, 'techub/login.html', context=context)
    elif request.method == 'POST':

        login_user = request.POST.get('login')
        senha = request.POST.get('senha')
        user = authenticate(username=login_user, password=senha)
        if user:
            login_django(request, user)
            success_url = reverse_lazy('TecHub:hub')
            return HttpResponseRedirect(redirect_to=success_url)
        else:
            unsuccess_url = reverse_lazy('TecHub:login')
            return HttpResponseRedirect(redirect_to=unsuccess_url)


def barra_navegacao(request):
    if request.method == "GET":
        itens_navegacao = NavItem.objects.order_by('-id')
        return render(request, 'techub/barra_navegacao.html', {'itens_navegacao': itens_navegacao})


@login_required(login_url='login')
def hub_digital(request):
    if request.method == 'GET':
        instituicoes_usuario = InformacaoClienteOpenFinance.objects.all().filter(usuario=request.user)
        itens_navegacao = NavItem.objects.order_by('-id')
        data = cria_data_por_extenso()
        user_info = request.user
        url = reverse_lazy('TecHub:hub')
        context = {
            'itens': itens_navegacao,
            'user_info': user_info,
            'data': data,
            'url': url,
            'instituicoes': instituicoes_usuario
        }
        return render(request, template_name='techub/hub/hub_index.html', context=context)
    if request.method == 'POST':
        pagina = request.POST.get('name')
        success_url = reverse_lazy('TecHub:hub')
        if pagina == 'Open Finance':
            success_url = reverse_lazy('TecHub:open_finance')
        return HttpResponseRedirect(redirect_to=success_url)


@login_required(login_url='login')
def open_finance(request):
    itens_navegacao = NavItem.objects.order_by('-id')
    data = cria_data_por_extenso()
    user_info = request.user
    info_instituicoes = Instituicao.objects.all().order_by('nome')
    url = reverse_lazy('TecHub:open_finance')

    context = {
        'itens': itens_navegacao,
        'info_instituicoes': info_instituicoes,
        'user_info': user_info,
        'data': data,
        'url': url
    }

    if request.method == 'GET':
        return render(request, template_name='techub/hub/open_finance.html', context=context)
    elif request.method == 'POST':
        instituicao = request.POST['instituicao']
        agencia = request.POST.get('agencia')
        conta = request.POST.get('conta')
        senha = request.POST.get('senha')
        user_id = request.user.id

        # Query da instituicao
        result_query_intituicao = Instituicao.objects.filter(id=instituicao).values('id').first()
        result_query_user_instituicao = InfoClienteInstituicao.objects.filter(Instituicao_id=instituicao).values(
            'Instituicao_id').first()

        if not result_query_user_instituicao:
            result_query_user_instituicao = {'Instituicao_id': 0}
        if not result_query_intituicao:
            result_query_intituicao = {'id': 0}

        # Query do usuário
        result_query_user_info = InfoClienteInstituicao.objects.filter(agencia=agencia, conta=conta, senha=senha,
                                                                       usuario=user_id).values('id').first()

        if result_query_intituicao["id"] == result_query_user_instituicao[
            "Instituicao_id"] and result_query_user_info != None:
            # cria um novo registro no banco de dados
            registro_user = InformacaoClienteOpenFinance(usuario=request.user,
                                                         instituicao_user=Instituicao.objects.get(id=instituicao),
                                                         info_instituicao_user=InfoClienteInstituicao.objects.get(
                                                             id=result_query_user_info["id"]))
            registro_user.save()
            success_url = reverse_lazy('TecHub:hub')
            return HttpResponseRedirect(redirect_to=success_url)
        messages.error(request, 'Não foi possível cadastrar a intituição fiananceira!!')
        return render(request, template_name='techub/hub/open_finance.html', context=context)


def instituicao_view(request, pk):
    instituicao = InformacaoClienteOpenFinance.objects.get(pk=pk)

    # Formatação dos saldos bancários para a formatação brasileira
    saldo_bancario = float(instituicao.info_instituicao_user.saldo_bancario)
    saldo_bancario = f'{saldo_bancario:,.2f}'.replace(',', '_').replace('.', ',').replace('_', '.')
    saldo_drex = instituicao.info_instituicao_user.saldo_drex
    saldo_drex = f'{saldo_drex:,.2f}'.replace(',', '_').replace('.', ',').replace('_', '.')

    user_info = request.user
    data = cria_data_por_extenso()
    itens_navegacao = NavItem.objects.order_by('-id')
    url = reverse_lazy('TecHub:hub')

    context = {
        'instituicao': instituicao,
        'saldo_bancario': saldo_bancario,
        'saldo_drex': saldo_drex,
        'user_info': user_info,
        'data': data,
        'itens': itens_navegacao,
        'url': url
    }
    if request.method == 'GET':
        return render(request, template_name='techub/hub/instituicao_view.html', context=context)


def realiza_cambio(request, pk):
    instituicao = InformacaoClienteOpenFinance.objects.get(pk=pk)
    user_info = request.user
    data = cria_data_por_extenso()
    itens_navegacao = NavItem.objects.order_by('-id')
    form = CambioForm()
    url = reverse_lazy('TecHub:hub')
    saldo_bancario = float(instituicao.info_instituicao_user.saldo_bancario)
    saldo_bancario = f'{saldo_bancario:,.2f}'.replace(',', '_').replace('.', ',').replace('_', '.')
    saldo_drex = instituicao.info_instituicao_user.saldo_drex
    saldo_drex = f'{saldo_drex:,.2f}'.replace(',', '_').replace('.', ',').replace('_', '.')

    context = {
        'instituicao': instituicao,
        'saldo_bancario': saldo_bancario,
        'saldo_drex': saldo_drex,
        'user_info': user_info,
        'data': data,
        'itens': itens_navegacao,
        'form': form,
        'url': url
    }

    if request.method == 'GET':
        return render(request, template_name='techub/hub/cambio.html', context=context)
    else:
        form = CambioForm(request.POST)
        if form.is_valid():
            try:
                form.cleaned_data
                chave_de_busca = \
                    InformacaoClienteOpenFinance.objects.filter(pk=pk).values('info_instituicao_user').first()[
                        'info_instituicao_user']
                info_cliente_instituicao = InfoClienteInstituicao.objects.get(pk=chave_de_busca)
                saldo_bancario = info_cliente_instituicao.saldo_bancario
                valor_cambio = float(str(form.cleaned_data['valor_cambio']).replace(".", "") \
                                     .replace(",", "."))
                if valor_cambio == 0:
                    raise ValidationError('O valor não pode ser R$ 0,00')
                elif valor_cambio <= saldo_bancario:
                    valor_cambio = Decimal(valor_cambio)
                    novo_saldo_bancario = saldo_bancario - valor_cambio
                    novo_saldo_drex = valor_cambio
                    info_cliente_instituicao.saldo_bancario = novo_saldo_bancario
                    info_cliente_instituicao.saldo_drex += novo_saldo_drex
                    info_cliente_instituicao.save()
                    valor_cambio = f'{valor_cambio:,.2f}'.replace(",", "_") \
                        .replace(".", ",").replace("_", ".")
                    messages.success(request, f'Câmbio de R$ {valor_cambio} para X$ {valor_cambio}\
                     DREX realizado com sucesso!')
                else:
                    raise ValidationError('O valor não pode ser maior do que seu saldo bancário')
            except ValidationError as e:
                mensagem_erro = str(e).removeprefix("['").removesuffix("']")  # Converte o erro em uma mensagem de texto
                messages.error(request, mensagem_erro)
                saldo_bancario = f'{saldo_bancario:,.2f}'.replace(",", "_") \
                    .replace(".", ",").replace("_", ".")
                context["valor_disponivel"] = saldo_bancario

TecHub/templates/techub/hub/cambio.html
{% extends "barra_navegacao.html" %}
{% load static %}
{% block title %}TecHub{% endblock %}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/estilo_cambio.css' %}">
{% endblock %}

{% block conteudo %}
    <input type="hidden" id="url" value="{{ url }}"/>
    <div id="conteudo-hub-pai">
        <section id="conteudo-hub"> 
            <div class="container-hub">
                <p class='bem-vindo'>
                    <span class='bem-vindo-nome'><b>Bem-vindo {{ user_info.first_name }}</b></span><br>
                    <span class='data'>{{data}}</span>
                </p>
            </div>
            <div id="container-info-instituicao">
                <div id="instituicao-usuario">
                    <div class="container-foto-nome">
                        <div class="container-foto">
                            <i>
                                <img  class='foto-instituicao' src="{{ instituicao.instituicao_user.foto_instituicao }}" alt="">
                            </i> 
                        </div>
                        <div id="container-nome-instituicao" >
                            <div class="nome-instituicao">{{instituicao.instituicao_user}}</div>
                        
                            <div id="container-info">
                                <div class="container-label"><label for="input-agencia">AGÊNCIA</label></div>
                                <input id="input-agencia" readonly type="text" value="{{instituicao.info_instituicao_user.agencia}}">
                                <br><div class="container-label"><label for="input-conta">CONTA</label></div>
                                <input id="input-agencia" readonly type="text" value="{{instituicao.info_instituicao_user.conta}}">
                            </div> 
                        </div>
                        <div class="container-foto">
                            <i>
                                <img  class='foto-instituicao' src="{{ instituicao.instituicao_user.foto_instituicao }}" alt="">
                            </i> 
                        </div>                    
                    </div>  
                </div>
                <hr class="separador">
                <div id="container-conteudo">
                    <div id="container-saldos">
                        <div id="container-real">
                            <label class="label-saldo" for="saldo_real">Saldo Bancário</label>
                            <input type="text" id="saldo_real" class="saldo" value=" R$ {{saldo_bancario}}" readonly>
                        </div>
                        <div id="container-drex">
                            <label class="label-saldo" for="saldo_drex">Saldo DREX</label>
                            <input type="text" id="saldo_drex" class="saldo" value=" X$ {{saldo_drex}}" readonly>  
                        </div>
                    </div>
                    
                        <form id="form" method="post">
                            {% csrf_token %}
    
                            <div id="container-input">
                                {{ form }}
                            </div>

                            <div id="container-btns">
                                <button class="btn" id="btn-voltar">
                                    <a href="{% url 'TecHub:instituicao_view' pk=instituicao.pk %}">Voltar</a>
                                </button>
                                <button class="btn" type="submit">Converter</button>
                            </div>
                        </form>

                </div>
            </div>
        </section>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
        {% for m in messages %}
            <script>
                Swal.fire({
                    "title": "{{m}}",
                    "text": "Saldo disponível: R$ {{valor_disponivel}}",
                    "icon": "error",
                    "confirmButton": "OK",
                })
            </script>
        {% endfor %}
    {% endif %}  
{% endblock conteudo %} 
{% block script %}
    <script src="{% static 'code.jquery.com_jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'jquery.mask.min.js' %}"></script>
    <script>
        $(document).ready(function () {
        var url = $('#url').val();
        if (url == '/hub/') {
            $('#hub').attr('style', 'background-color: #b5a1b1dd!important; border-radius: 10px');
        }
        
        $('#id_valor_cambio').mask("#.##0,90", {reverse: true})       
        
        $(':input').on('focus', function() {
            this.dataset.placeholder = this.placeholder;
            this.placeholder = '';
            }).on('blur', function(){
            this.placeholder = this.dataset.placeholder;
        });
    })
    </script>
{% endblock %}

TecHub/templates/techub/hub/hub_index.html
{% extends "barra_navegacao.html" %}    
{% load static %}
{% block title %}TecHub{% endblock %}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/estilo_hub.css' %}">
{% endblock %}

{% block conteudo %}
    <input type="hidden" id="url" value="{{ url }}"/>
    <div id="conteudo-hub-pai">
        <section id="conteudo-hub"> 
            <div class="container-hub">
                <p class='bem-vindo'>
                    <span class='bem-vindo-nome'><b>Bem-vindo {{ user_info.first_name }}</b></span><br>
                    <span class='data'>{{data}}</span>
                </p>
            </div>
            <div id="instituicoes-user">   
                {% for instituicao in instituicoes %}
                    <div id="instituicao-usuario">
                        <div class="container-foto-nome">
                            <div class="container-foto">
                                <i>
                                    <img  class='foto-instituicao' src="{{ instituicao.instituicao_user.foto_instituicao }}" alt="">
                                </i> 
                            </div>
                            <div id="container-nome-instituicao" >
                                <div class="nome-instituicao">{{instituicao.instituicao_user}}</div>
                            </div>
                            <div id="container-info">
                                <div class="container-label"><label for="input-agencia">AGÊNCIA</label></div>
                                <input id="input-agencia" readonly type="text" value="{{instituicao.info_instituicao_user.agencia}}">
                                <br><div class="container-label"><label for="input-conta">CONTA</label></div>
                                <input id="input-agencia" readonly type="text" value="{{instituicao.info_instituicao_user.conta}}">
                            </div>                     
                        </div>
                        <hr class="separador">
                        <div id="container-saldos">
                            <div id="container-real">
                                <label class="label-saldo" for="saldo_real">Saldo Bancário:</label>
                                <input type="text" id="saldo_real" class="saldo" value=" R$ {{instituicao.info_instituicao_user.saldo_bancario}}" readonly>
                            </div><br>
                            <div id="container-drex">
                                <label class="label-saldo" for="saldo_drex">Saldo DREX:</label>
                                <input type="text" id="saldo_drex" class="saldo" value=" X$ {{instituicao.info_instituicao_user.saldo_drex}}" readonly>  
                            </div>
                        </div> 
                        <div id="container-btn">
                            <button id="btn-acessar"><a href="{% url 'TecHub:instituicao_view' pk=instituicao.id %}">Acessar</a></button>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
    </div>  
{% endblock conteudo %}
{% block script %}
    <script src="{% static 'jquery.mask.min.js' %}"></script>
    <script src="{% static 'code.jquery.com_jquery-3.7.1.min.js' %}"></script>
    <script>
        $(document).ready(function () {
        var url = $('#url').val();
        if (url == '/hub/') {
            $('#hub').attr('style', 'background-color: #b5a1b1dd!important; border-radius: 10px');
        }

        $('#saldo_real').val().mask('000.000.000.000.000,00', {reverse: true});
    })

    </script>
{% endblock %}

TecHub/templates/techub/hub/instituicao_view.html
{% extends "barra_navegacao.html" %}
{% load static %}
{% block title %}TecHub{% endblock %}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/estilo_instituicao_view.css' %}">
{% endblock %}

{% block conteudo %}
    <input type="hidden" id="url" value="{{ url }}"/>
    <div id="conteudo-hub-pai">
        <section id="conteudo-hub"> 
            <div class="container-hub">
                <p class='bem-vindo'>
                    <span class='bem-vindo-nome'><b>Bem-vindo {{ user_info.first_name }}</b></span><br>
                    <span class='data'>{{data}}</span>
                </p>
            </div>
            <div id="container-info-instituicao">
                <div id="instituicao-usuario">
                    <div class="container-foto-nome">
                        <div class="container-foto">
                            <i>
                                <img  class='foto-instituicao' src="{{ instituicao.instituicao_user.foto_instituicao }}" alt="">
                            </i> 
                        </div>
                        <div id="container-nome-instituicao" >
                            <div class="nome-instituicao">{{instituicao.instituicao_user}}</div>
                        
                            <div id="container-info">
                                <div class="container-label"><label for="input-agencia">AGÊNCIA</label></div>
                                <input id="input-agencia" readonly type="text" value="{{instituicao.info_instituicao_user.agencia}}">
                                <br><div class="container-label"><label for="input-conta">CONTA</label></div>
                                <input id="input-agencia" readonly type="text" value="{{instituicao.info_instituicao_user.conta}}">
                            </div> 
                        </div>
                        <div class="container-foto">
                            <i>
                                <img  class='foto-instituicao' src="{{ instituicao.instituicao_user.foto_instituicao }}" alt="">
                            </i> 
                        </div>                    
                    </div>  
                </div>
                <hr class="separador">
                <div id="container-conteudo">
                    <div id="container-saldos">
                        <div id="container-real">
                            <label class="label-saldo" for="saldo_real">Saldo Bancário</label>
                            <input type="text" id="saldo_real" class="saldo" value=" R$ {{saldo_bancario}}" readonly>
                        </div>
                        <div id="container-drex">
                            <label class="label-saldo" for="saldo_drex">Saldo DREX</label>
                            <input type="text" id="saldo_drex" class="saldo" value=" X$ {{saldo_drex}}" readonly>  
                        </div>
                    </div> 
                    <div id="container-pai-btns">
                        <div id="container-botoes-navegacao">
                            <div class="container-btn">
                                <button class="btn-navegacao">
                                    <a href="{% url 'TecHub:realiza_cambio' pk=instituicao.pk %}">
                                        <i class="fa-solid fa-solid fa-right-left"><br><br><span style="font-family: 'Inter', sans-serif;">Câmbio</span></i>
                                    </a>  
                                </button>
                            </div>
                            <div class="container-btn">
                                <button class="btn-navegacao">
                                    <a href="{% url 'TecHub:realiza_tranferencia' pk=instituicao.pk %}">
                                        <i class="fa-solid fa-money-bill-transfer"><br><br><span style="font-family: 'Inter', sans-serif;">Transferência</span></i>
                                    </a>  
                                </button>
                            </div>
                        </div>
                        <div id="container-btn-voltar">
                            <button id="btn-voltar">
                                <a href="{% url 'TecHub:hub' %}">Voltar</a>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
        {% for m in messages %}
            <script>
                Swal.fire({
                    "title": "{{m}}",
                    "icon": "success",
                    "confirmButton": "OK",
                })
            </script>
        {% endfor %}
    {% endif %}  
    {% endblock conteudo %}
    {% block script %}
    <script src="{% static 'code.jquery.com_jquery-3.7.1.min.js' %}"></script>
    <script>
        $(document).ready(function () {
        var url = $('#url').val();
        console.log(url)    
        if (url == '/hub/') {
            $('#hub').attr('style', 'background-color: #b5a1b1dd!important; border-radius: 10px');
        }
    })
    </script>
{% endblock %}

    